### ISSUE TITLE
Links you might be interested in

### ISSUE THREAD

**Issue by kmarekspartz** [bsundsrud/community#1]
- https://openreferral.org/
- http://ohanapi.org/
- http://purplebinder.com/
- https://www.mrelief.com/

@to-json sent me your way.

**Comment by kmarekspartz** [comment]
Oh, and https://www.auntbertha.com/

**Comment by bsundsrud** [comment]
Sorry I didn't get back to you sooner, I got busy with other things and then was out of town last week.  I was planning on getting in touch when I had slightly more than a crude prototype.  Those are great links (especially auntbertha).  

Our vision for this is focused on the discovery piece, meant to be used by either potential clients or people who can offer referrals (teachers or other social workers) to find programs that fit the client without inundating them with programs that they may or may not qualify for.  

If there's something out there that already does this, I'd love to see it.  This is something where we're trying to fill a current need so if I could just deploy/extend something pre-existing that would be great.

I mostly started this in Rust because I've been curious to have a real project to try out the language.
